USE onlineretail;

CREATE TABLE customer(
ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(255),
ADDRES VARCHAR(255)
);

CREATE TABLE seller(
ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(255),
customer_id INT,
FOREIGN KEY (customer_id) REFERENCES customer(ID)
);

CREATE TABLE category(
ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(255),
seller_id INT,
FOREIGN KEY (seller_id) REFERENCES seller(ID)
);

CREATE TABLE product(
ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NAME_PRODUCT VARCHAR(255),
PRICE INT,
category_id INT,
FOREIGN KEY (category_id) REFERENCES category(ID)
);

CREATE TABLE shopping_order(
ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
product_id INT,
FOREIGN KEY (prouct_id) REFERENCES product(ID)
);

SHOW TABLES;

SELECT * FROM CUSTOMER;


